// CodeMon Creature Database & Stat Generator

const CODEMON_TYPES = {
  BUG: 'bug',
  CODE: 'code',
  MEMORY: 'memory',
  LOGIC: 'logic',
  FLOW: 'flow'
};

// Generated by scripts/gen_roster.py (seeded, so it regenerates identically).
const CODEMON_SPECIES = [
  {
    id: 1,
    name: "Byteling",
    type: CODEMON_TYPES.BUG,
    baseHp: 32,
    baseAtk: 25,
    baseDef: 16,
    baseSp: 22,
    baseSpd: 19,
    exp: 0,
    expToLevel: 60,
    catchRate: 210,
    moves: ["Bite", "Scratch", "Harden"]
  },
  {
    id: 2,
    name: "BitRiot",
    type: CODEMON_TYPES.CODE,
    baseHp: 35,
    baseAtk: 19,
    baseDef: 22,
    baseSp: 16,
    baseSpd: 21,
    exp: 0,
    expToLevel: 60,
    catchRate: 210,
    moves: ["StringConcat", "DebugAttack", "Recover"]
  },
  {
    id: 3,
    name: "Memorex",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 29,
    baseAtk: 26,
    baseDef: 21,
    baseSp: 26,
    baseSpd: 16,
    exp: 0,
    expToLevel: 60,
    catchRate: 210,
    moves: ["CacheStore", "LeakDetect", "Recover"]
  },
  {
    id: 4,
    name: "Logix",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 36,
    baseAtk: 20,
    baseDef: 21,
    baseSp: 22,
    baseSpd: 16,
    exp: 0,
    expToLevel: 60,
    catchRate: 210,
    moves: ["IfStatement", "StackOverflow", "Tackle"]
  },
  {
    id: 5,
    name: "Flowy",
    type: CODEMON_TYPES.FLOW,
    baseHp: 32,
    baseAtk: 23,
    baseDef: 21,
    baseSp: 30,
    baseSpd: 16,
    exp: 0,
    expToLevel: 60,
    catchRate: 210,
    moves: ["AsyncWave", "CallbackStrike", "Harden"]
  },
  {
    id: 6,
    name: "Grubyte",
    type: CODEMON_TYPES.BUG,
    baseHp: 30,
    baseAtk: 31,
    baseDef: 22,
    baseSp: 23,
    baseSpd: 26,
    exp: 0,
    expToLevel: 63,
    catchRate: 206,
    moves: ["Scratch", "Bite", "Scratch"]
  },
  {
    id: 7,
    name: "Compilr",
    type: CODEMON_TYPES.CODE,
    baseHp: 25,
    baseAtk: 24,
    baseDef: 21,
    baseSp: 19,
    baseSpd: 13,
    exp: 0,
    expToLevel: 63,
    catchRate: 206,
    moves: ["Crash", "DebugAttack", "Harden"]
  },
  {
    id: 8,
    name: "Cachette",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 28,
    baseAtk: 22,
    baseDef: 26,
    baseSp: 24,
    baseSpd: 19,
    exp: 0,
    expToLevel: 63,
    catchRate: 206,
    moves: ["DataShift", "LeakDetect", "Tackle"]
  },
  {
    id: 9,
    name: "Booleen",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 33,
    baseAtk: 30,
    baseDef: 24,
    baseSp: 23,
    baseSpd: 27,
    exp: 0,
    expToLevel: 63,
    catchRate: 206,
    moves: ["BooleanFlip", "LogicalAnd", "Recover"]
  },
  {
    id: 10,
    name: "Asyncro",
    type: CODEMON_TYPES.FLOW,
    baseHp: 24,
    baseAtk: 20,
    baseDef: 16,
    baseSp: 27,
    baseSpd: 17,
    exp: 0,
    expToLevel: 63,
    catchRate: 206,
    moves: ["CallbackStrike", "AsyncWave", "Tackle"]
  },
  {
    id: 11,
    name: "Nibbler",
    type: CODEMON_TYPES.BUG,
    baseHp: 31,
    baseAtk: 32,
    baseDef: 21,
    baseSp: 17,
    baseSpd: 13,
    exp: 0,
    expToLevel: 66,
    catchRate: 202,
    moves: ["Bite", "Scratch", "Tackle"]
  },
  {
    id: 12,
    name: "Syntaxa",
    type: CODEMON_TYPES.CODE,
    baseHp: 27,
    baseAtk: 21,
    baseDef: 24,
    baseSp: 30,
    baseSpd: 18,
    exp: 0,
    expToLevel: 66,
    catchRate: 202,
    moves: ["DebugAttack", "StringConcat", "Harden"]
  },
  {
    id: 13,
    name: "Heapster",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 26,
    baseAtk: 28,
    baseDef: 27,
    baseSp: 22,
    baseSpd: 28,
    exp: 0,
    expToLevel: 66,
    catchRate: 202,
    moves: ["LeakDetect", "CacheStore", "Scratch"]
  },
  {
    id: 14,
    name: "Truthor",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 35,
    baseAtk: 30,
    baseDef: 23,
    baseSp: 28,
    baseSpd: 16,
    exp: 0,
    expToLevel: 66,
    catchRate: 202,
    moves: ["LogicalAnd", "StackOverflow", "Harden"]
  },
  {
    id: 15,
    name: "Streamix",
    type: CODEMON_TYPES.FLOW,
    baseHp: 33,
    baseAtk: 27,
    baseDef: 26,
    baseSp: 22,
    baseSpd: 16,
    exp: 0,
    expToLevel: 66,
    catchRate: 202,
    moves: ["PromiseChain", "AsyncWave", "Tackle"]
  },
  {
    id: 16,
    name: "Weevil",
    type: CODEMON_TYPES.BUG,
    baseHp: 34,
    baseAtk: 26,
    baseDef: 22,
    baseSp: 17,
    baseSpd: 13,
    exp: 0,
    expToLevel: 69,
    catchRate: 198,
    moves: ["Scratch", "Bite", "Recover"]
  },
  {
    id: 17,
    name: "Kernelix",
    type: CODEMON_TYPES.CODE,
    baseHp: 26,
    baseAtk: 26,
    baseDef: 28,
    baseSp: 19,
    baseSpd: 15,
    exp: 0,
    expToLevel: 69,
    catchRate: 198,
    moves: ["StringConcat", "Crash", "Tackle"]
  },
  {
    id: 18,
    name: "Ramoth",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 26,
    baseAtk: 24,
    baseDef: 24,
    baseSp: 29,
    baseSpd: 20,
    exp: 0,
    expToLevel: 69,
    catchRate: 198,
    moves: ["CacheStore", "LeakDetect", "Harden"]
  },
  {
    id: 19,
    name: "Ifelsa",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 35,
    baseAtk: 20,
    baseDef: 21,
    baseSp: 17,
    baseSpd: 25,
    exp: 0,
    expToLevel: 69,
    catchRate: 198,
    moves: ["StackOverflow", "IfStatement", "Harden"]
  },
  {
    id: 20,
    name: "Promisa",
    type: CODEMON_TYPES.FLOW,
    baseHp: 22,
    baseAtk: 18,
    baseDef: 26,
    baseSp: 19,
    baseSpd: 22,
    exp: 0,
    expToLevel: 69,
    catchRate: 198,
    moves: ["AsyncWave", "CallbackStrike", "Tackle"]
  },
  {
    id: 21,
    name: "Mothrun",
    type: CODEMON_TYPES.BUG,
    baseHp: 23,
    baseAtk: 28,
    baseDef: 19,
    baseSp: 20,
    baseSpd: 27,
    exp: 0,
    expToLevel: 72,
    catchRate: 194,
    moves: ["Bite", "Scratch", "Recover"]
  },
  {
    id: 22,
    name: "Bytecode",
    type: CODEMON_TYPES.CODE,
    baseHp: 35,
    baseAtk: 22,
    baseDef: 20,
    baseSp: 19,
    baseSpd: 18,
    exp: 0,
    expToLevel: 72,
    catchRate: 194,
    moves: ["Crash", "StringConcat", "Recover"]
  },
  {
    id: 23,
    name: "Bufferly",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 27,
    baseAtk: 20,
    baseDef: 23,
    baseSp: 16,
    baseSpd: 12,
    exp: 0,
    expToLevel: 72,
    catchRate: 194,
    moves: ["DataShift", "LeakDetect", "Scratch"]
  },
  {
    id: 24,
    name: "Gatewyrm",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 24,
    baseAtk: 21,
    baseDef: 22,
    baseSp: 25,
    baseSpd: 17,
    exp: 0,
    expToLevel: 72,
    catchRate: 194,
    moves: ["IfStatement", "LogicalAnd", "Harden"]
  },
  {
    id: 25,
    name: "Awaitor",
    type: CODEMON_TYPES.FLOW,
    baseHp: 36,
    baseAtk: 20,
    baseDef: 19,
    baseSp: 29,
    baseSpd: 22,
    exp: 0,
    expToLevel: 72,
    catchRate: 194,
    moves: ["CallbackStrike", "PromiseChain", "Scratch"]
  },
  {
    id: 26,
    name: "Larvex",
    type: CODEMON_TYPES.BUG,
    baseHp: 24,
    baseAtk: 21,
    baseDef: 25,
    baseSp: 20,
    baseSpd: 18,
    exp: 0,
    expToLevel: 75,
    catchRate: 190,
    moves: ["Scratch", "Bite", "Tackle"]
  },
  {
    id: 27,
    name: "Lintbeast",
    type: CODEMON_TYPES.CODE,
    baseHp: 25,
    baseAtk: 32,
    baseDef: 27,
    baseSp: 16,
    baseSpd: 26,
    exp: 0,
    expToLevel: 75,
    catchRate: 190,
    moves: ["DebugAttack", "StringConcat", "Tackle"]
  },
  {
    id: 28,
    name: "Paginar",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 32,
    baseAtk: 25,
    baseDef: 16,
    baseSp: 29,
    baseSpd: 15,
    exp: 0,
    expToLevel: 75,
    catchRate: 190,
    moves: ["LeakDetect", "CacheStore", "Scratch"]
  },
  {
    id: 29,
    name: "Predika",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 30,
    baseAtk: 21,
    baseDef: 24,
    baseSp: 18,
    baseSpd: 15,
    exp: 0,
    expToLevel: 75,
    catchRate: 190,
    moves: ["BooleanFlip", "IfStatement", "Recover"]
  },
  {
    id: 30,
    name: "Yieldle",
    type: CODEMON_TYPES.FLOW,
    baseHp: 25,
    baseAtk: 28,
    baseDef: 27,
    baseSp: 29,
    baseSpd: 22,
    exp: 0,
    expToLevel: 75,
    catchRate: 190,
    moves: ["PromiseChain", "CallbackStrike", "Harden"]
  },
  {
    id: 31,
    name: "Crawlit",
    type: CODEMON_TYPES.BUG,
    baseHp: 29,
    baseAtk: 18,
    baseDef: 14,
    baseSp: 17,
    baseSpd: 25,
    exp: 0,
    expToLevel: 78,
    catchRate: 186,
    moves: ["Bite", "Scratch", "Harden"]
  },
  {
    id: 32,
    name: "Refactor",
    type: CODEMON_TYPES.CODE,
    baseHp: 26,
    baseAtk: 20,
    baseDef: 26,
    baseSp: 17,
    baseSpd: 28,
    exp: 0,
    expToLevel: 78,
    catchRate: 186,
    moves: ["StringConcat", "Crash", "Tackle"]
  },
  {
    id: 33,
    name: "Swapling",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 22,
    baseAtk: 30,
    baseDef: 17,
    baseSp: 30,
    baseSpd: 13,
    exp: 0,
    expToLevel: 78,
    catchRate: 186,
    moves: ["CacheStore", "DataShift", "Recover"]
  },
  {
    id: 34,
    name: "Conditio",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 29,
    baseAtk: 26,
    baseDef: 23,
    baseSp: 29,
    baseSpd: 26,
    exp: 0,
    expToLevel: 78,
    catchRate: 186,
    moves: ["LogicalAnd", "IfStatement", "Scratch"]
  },
  {
    id: 35,
    name: "Pipelyn",
    type: CODEMON_TYPES.FLOW,
    baseHp: 25,
    baseAtk: 27,
    baseDef: 17,
    baseSp: 23,
    baseSpd: 22,
    exp: 0,
    expToLevel: 78,
    catchRate: 186,
    moves: ["AsyncWave", "PromiseChain", "Recover"]
  },
  {
    id: 36,
    name: "Antsy",
    type: CODEMON_TYPES.BUG,
    baseHp: 38,
    baseAtk: 43,
    baseDef: 39,
    baseSp: 41,
    baseSpd: 30,
    exp: 0,
    expToLevel: 121,
    catchRate: 112,
    moves: ["Scratch", "Bite", "Recover"]
  },
  {
    id: 37,
    name: "Assembly",
    type: CODEMON_TYPES.CODE,
    baseHp: 37,
    baseAtk: 32,
    baseDef: 32,
    baseSp: 39,
    baseSpd: 30,
    exp: 0,
    expToLevel: 121,
    catchRate: 112,
    moves: ["Crash", "DebugAttack", "Scratch"]
  },
  {
    id: 38,
    name: "Leakage",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 47,
    baseAtk: 36,
    baseDef: 33,
    baseSp: 39,
    baseSpd: 39,
    exp: 0,
    expToLevel: 121,
    catchRate: 112,
    moves: ["DataShift", "LeakDetect", "Recover"]
  },
  {
    id: 39,
    name: "Xorvus",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 42,
    baseAtk: 44,
    baseDef: 28,
    baseSp: 42,
    baseSpd: 38,
    exp: 0,
    expToLevel: 121,
    catchRate: 112,
    moves: ["StackOverflow", "IfStatement", "Scratch"]
  },
  {
    id: 40,
    name: "Chanelle",
    type: CODEMON_TYPES.FLOW,
    baseHp: 45,
    baseAtk: 41,
    baseDef: 40,
    baseSp: 43,
    baseSpd: 36,
    exp: 0,
    expToLevel: 121,
    catchRate: 112,
    moves: ["CallbackStrike", "AsyncWave", "Recover"]
  },
  {
    id: 41,
    name: "Hexapod",
    type: CODEMON_TYPES.BUG,
    baseHp: 39,
    baseAtk: 44,
    baseDef: 34,
    baseSp: 40,
    baseSpd: 34,
    exp: 0,
    expToLevel: 124,
    catchRate: 108,
    moves: ["Bite", "Scratch", "Harden"]
  },
  {
    id: 42,
    name: "Runtimer",
    type: CODEMON_TYPES.CODE,
    baseHp: 39,
    baseAtk: 32,
    baseDef: 37,
    baseSp: 36,
    baseSpd: 36,
    exp: 0,
    expToLevel: 124,
    catchRate: 108,
    moves: ["DebugAttack", "StringConcat", "Harden"]
  },
  {
    id: 43,
    name: "Allocat",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 42,
    baseAtk: 32,
    baseDef: 40,
    baseSp: 37,
    baseSpd: 32,
    exp: 0,
    expToLevel: 124,
    catchRate: 108,
    moves: ["LeakDetect", "DataShift", "Tackle"]
  },
  {
    id: 44,
    name: "Nandra",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 49,
    baseAtk: 39,
    baseDef: 29,
    baseSp: 43,
    baseSpd: 26,
    exp: 0,
    expToLevel: 124,
    catchRate: 108,
    moves: ["IfStatement", "LogicalAnd", "Harden"]
  },
  {
    id: 45,
    name: "Bufferra",
    type: CODEMON_TYPES.FLOW,
    baseHp: 49,
    baseAtk: 45,
    baseDef: 30,
    baseSp: 41,
    baseSpd: 35,
    exp: 0,
    expToLevel: 124,
    catchRate: 108,
    moves: ["PromiseChain", "CallbackStrike", "Recover"]
  },
  {
    id: 46,
    name: "Chitin",
    type: CODEMON_TYPES.BUG,
    baseHp: 48,
    baseAtk: 39,
    baseDef: 36,
    baseSp: 35,
    baseSpd: 40,
    exp: 0,
    expToLevel: 127,
    catchRate: 104,
    moves: ["Scratch", "Bite", "Recover"]
  },
  {
    id: 47,
    name: "Stacktrace",
    type: CODEMON_TYPES.CODE,
    baseHp: 42,
    baseAtk: 34,
    baseDef: 38,
    baseSp: 39,
    baseSpd: 26,
    exp: 0,
    expToLevel: 127,
    catchRate: 104,
    moves: ["StringConcat", "Crash", "Recover"]
  },
  {
    id: 48,
    name: "Garbagen",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 38,
    baseAtk: 32,
    baseDef: 41,
    baseSp: 35,
    baseSpd: 38,
    exp: 0,
    expToLevel: 127,
    catchRate: 104,
    moves: ["CacheStore", "LeakDetect", "Recover"]
  },
  {
    id: 49,
    name: "Inferro",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 44,
    baseAtk: 32,
    baseDef: 41,
    baseSp: 41,
    baseSpd: 28,
    exp: 0,
    expToLevel: 127,
    catchRate: 104,
    moves: ["BooleanFlip", "LogicalAnd", "Harden"]
  },
  {
    id: 50,
    name: "Backpres",
    type: CODEMON_TYPES.FLOW,
    baseHp: 42,
    baseAtk: 44,
    baseDef: 37,
    baseSp: 33,
    baseSpd: 37,
    exp: 0,
    expToLevel: 127,
    catchRate: 104,
    moves: ["AsyncWave", "CallbackStrike", "Tackle"]
  },
  {
    id: 51,
    name: "Swarmlet",
    type: CODEMON_TYPES.BUG,
    baseHp: 47,
    baseAtk: 45,
    baseDef: 29,
    baseSp: 32,
    baseSpd: 28,
    exp: 0,
    expToLevel: 130,
    catchRate: 100,
    moves: ["Bite", "Scratch", "Harden"]
  },
  {
    id: 52,
    name: "Segfault",
    type: CODEMON_TYPES.CODE,
    baseHp: 41,
    baseAtk: 32,
    baseDef: 39,
    baseSp: 43,
    baseSpd: 31,
    exp: 0,
    expToLevel: 130,
    catchRate: 100,
    moves: ["Crash", "StringConcat", "Harden"]
  },
  {
    id: 53,
    name: "Pointer",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 48,
    baseAtk: 44,
    baseDef: 38,
    baseSp: 32,
    baseSpd: 26,
    exp: 0,
    expToLevel: 130,
    catchRate: 100,
    moves: ["DataShift", "CacheStore", "Scratch"]
  },
  {
    id: 54,
    name: "Axiomon",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 46,
    baseAtk: 46,
    baseDef: 37,
    baseSp: 33,
    baseSpd: 32,
    exp: 0,
    expToLevel: 130,
    catchRate: 100,
    moves: ["LogicalAnd", "StackOverflow", "Tackle"]
  },
  {
    id: 55,
    name: "Throttle",
    type: CODEMON_TYPES.FLOW,
    baseHp: 46,
    baseAtk: 43,
    baseDef: 41,
    baseSp: 42,
    baseSpd: 40,
    exp: 0,
    expToLevel: 130,
    catchRate: 100,
    moves: ["CallbackStrike", "PromiseChain", "Recover"]
  },
  {
    id: 56,
    name: "Mandible",
    type: CODEMON_TYPES.BUG,
    baseHp: 38,
    baseAtk: 42,
    baseDef: 37,
    baseSp: 43,
    baseSpd: 39,
    exp: 0,
    expToLevel: 133,
    catchRate: 96,
    moves: ["Scratch", "Bite", "Harden"]
  },
  {
    id: 57,
    name: "Nullpoint",
    type: CODEMON_TYPES.CODE,
    baseHp: 40,
    baseAtk: 33,
    baseDef: 41,
    baseSp: 33,
    baseSpd: 29,
    exp: 0,
    expToLevel: 133,
    catchRate: 96,
    moves: ["DebugAttack", "StringConcat", "Recover"]
  },
  {
    id: 58,
    name: "Stackpup",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 48,
    baseAtk: 39,
    baseDef: 28,
    baseSp: 42,
    baseSpd: 41,
    exp: 0,
    expToLevel: 133,
    catchRate: 96,
    moves: ["LeakDetect", "CacheStore", "Harden"]
  },
  {
    id: 59,
    name: "Theorem",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 42,
    baseAtk: 38,
    baseDef: 40,
    baseSp: 36,
    baseSpd: 30,
    exp: 0,
    expToLevel: 133,
    catchRate: 96,
    moves: ["StackOverflow", "IfStatement", "Recover"]
  },
  {
    id: 60,
    name: "Debounce",
    type: CODEMON_TYPES.FLOW,
    baseHp: 45,
    baseAtk: 46,
    baseDef: 40,
    baseSp: 38,
    baseSpd: 38,
    exp: 0,
    expToLevel: 133,
    catchRate: 96,
    moves: ["PromiseChain", "CallbackStrike", "Tackle"]
  },
  {
    id: 61,
    name: "Pupate",
    type: CODEMON_TYPES.BUG,
    baseHp: 46,
    baseAtk: 44,
    baseDef: 28,
    baseSp: 44,
    baseSpd: 31,
    exp: 0,
    expToLevel: 136,
    catchRate: 92,
    moves: ["Bite", "Scratch", "Tackle"]
  },
  {
    id: 62,
    name: "Opcode",
    type: CODEMON_TYPES.CODE,
    baseHp: 40,
    baseAtk: 34,
    baseDef: 38,
    baseSp: 42,
    baseSpd: 42,
    exp: 0,
    expToLevel: 136,
    catchRate: 92,
    moves: ["StringConcat", "Crash", "Tackle"]
  },
  {
    id: 63,
    name: "Registra",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 45,
    baseAtk: 32,
    baseDef: 31,
    baseSp: 40,
    baseSpd: 36,
    exp: 0,
    expToLevel: 136,
    catchRate: 92,
    moves: ["CacheStore", "LeakDetect", "Recover"]
  },
  {
    id: 64,
    name: "Deducto",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 40,
    baseAtk: 35,
    baseDef: 31,
    baseSp: 38,
    baseSpd: 30,
    exp: 0,
    expToLevel: 136,
    catchRate: 92,
    moves: ["IfStatement", "StackOverflow", "Scratch"]
  },
  {
    id: 65,
    name: "Cascada",
    type: CODEMON_TYPES.FLOW,
    baseHp: 36,
    baseAtk: 36,
    baseDef: 33,
    baseSp: 40,
    baseSpd: 27,
    exp: 0,
    expToLevel: 136,
    catchRate: 92,
    moves: ["AsyncWave", "CallbackStrike", "Scratch"]
  },
  {
    id: 66,
    name: "Skitter",
    type: CODEMON_TYPES.BUG,
    baseHp: 42,
    baseAtk: 39,
    baseDef: 30,
    baseSp: 35,
    baseSpd: 29,
    exp: 0,
    expToLevel: 139,
    catchRate: 88,
    moves: ["Scratch", "Bite", "Tackle"]
  },
  {
    id: 67,
    name: "Bitshift",
    type: CODEMON_TYPES.CODE,
    baseHp: 45,
    baseAtk: 33,
    baseDef: 33,
    baseSp: 30,
    baseSpd: 42,
    exp: 0,
    expToLevel: 139,
    catchRate: 88,
    moves: ["Crash", "DebugAttack", "Harden"]
  },
  {
    id: 68,
    name: "Volatyl",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 43,
    baseAtk: 39,
    baseDef: 38,
    baseSp: 42,
    baseSpd: 38,
    exp: 0,
    expToLevel: 139,
    catchRate: 88,
    moves: ["DataShift", "LeakDetect", "Recover"]
  },
  {
    id: 69,
    name: "Syllogi",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 38,
    baseAtk: 46,
    baseDef: 31,
    baseSp: 38,
    baseSpd: 42,
    exp: 0,
    expToLevel: 139,
    catchRate: 88,
    moves: ["BooleanFlip", "IfStatement", "Tackle"]
  },
  {
    id: 70,
    name: "Currenta",
    type: CODEMON_TYPES.FLOW,
    baseHp: 42,
    baseAtk: 39,
    baseDef: 32,
    baseSp: 34,
    baseSpd: 42,
    exp: 0,
    expToLevel: 139,
    catchRate: 88,
    moves: ["CallbackStrike", "AsyncWave", "Tackle"]
  },
  {
    id: 71,
    name: "Beetlow",
    type: CODEMON_TYPES.BUG,
    baseHp: 58,
    baseAtk: 51,
    baseDef: 49,
    baseSp: 50,
    baseSpd: 44,
    exp: 0,
    expToLevel: 182,
    catchRate: 20,
    moves: ["Bite", "Scratch", "Harden"]
  },
  {
    id: 72,
    name: "Forkling",
    type: CODEMON_TYPES.CODE,
    baseHp: 52,
    baseAtk: 54,
    baseDef: 44,
    baseSp: 52,
    baseSpd: 48,
    exp: 0,
    expToLevel: 182,
    catchRate: 20,
    moves: ["DebugAttack", "Crash", "Recover"]
  },
  {
    id: 73,
    name: "Bitmapp",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 61,
    baseAtk: 54,
    baseDef: 46,
    baseSp: 58,
    baseSpd: 45,
    exp: 0,
    expToLevel: 182,
    catchRate: 20,
    moves: ["LeakDetect", "DataShift", "Harden"]
  },
  {
    id: 74,
    name: "Paradox",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 54,
    baseAtk: 50,
    baseDef: 56,
    baseSp: 48,
    baseSpd: 44,
    exp: 0,
    expToLevel: 182,
    catchRate: 20,
    moves: ["LogicalAnd", "IfStatement", "Harden"]
  },
  {
    id: 75,
    name: "Rivulet",
    type: CODEMON_TYPES.FLOW,
    baseHp: 60,
    baseAtk: 46,
    baseDef: 48,
    baseSp: 57,
    baseSpd: 50,
    exp: 0,
    expToLevel: 182,
    catchRate: 20,
    moves: ["PromiseChain", "CallbackStrike", "Scratch"]
  },
  {
    id: 76,
    name: "Vermin",
    type: CODEMON_TYPES.BUG,
    baseHp: 52,
    baseAtk: 57,
    baseDef: 42,
    baseSp: 50,
    baseSpd: 46,
    exp: 0,
    expToLevel: 185,
    catchRate: 20,
    moves: ["Scratch", "Bite", "Scratch"]
  },
  {
    id: 77,
    name: "Daemon",
    type: CODEMON_TYPES.CODE,
    baseHp: 63,
    baseAtk: 57,
    baseDef: 44,
    baseSp: 55,
    baseSpd: 55,
    exp: 0,
    expToLevel: 185,
    catchRate: 20,
    moves: ["StringConcat", "Crash", "Harden"]
  },
  {
    id: 78,
    name: "Indexia",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 57,
    baseAtk: 50,
    baseDef: 42,
    baseSp: 45,
    baseSpd: 41,
    exp: 0,
    expToLevel: 185,
    catchRate: 20,
    moves: ["CacheStore", "DataShift", "Scratch"]
  },
  {
    id: 79,
    name: "Tautolo",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 60,
    baseAtk: 49,
    baseDef: 56,
    baseSp: 54,
    baseSpd: 54,
    exp: 0,
    expToLevel: 185,
    catchRate: 20,
    moves: ["StackOverflow", "BooleanFlip", "Recover"]
  },
  {
    id: 80,
    name: "Eddyon",
    type: CODEMON_TYPES.FLOW,
    baseHp: 53,
    baseAtk: 54,
    baseDef: 56,
    baseSp: 44,
    baseSpd: 56,
    exp: 0,
    expToLevel: 185,
    catchRate: 20,
    moves: ["AsyncWave", "CallbackStrike", "Tackle"]
  },
  {
    id: 81,
    name: "Grubbin",
    type: CODEMON_TYPES.BUG,
    baseHp: 64,
    baseAtk: 46,
    baseDef: 49,
    baseSp: 50,
    baseSpd: 42,
    exp: 0,
    expToLevel: 188,
    catchRate: 20,
    moves: ["Bite", "Scratch", "Harden"]
  },
  {
    id: 82,
    name: "Regexor",
    type: CODEMON_TYPES.CODE,
    baseHp: 51,
    baseAtk: 57,
    baseDef: 49,
    baseSp: 50,
    baseSpd: 46,
    exp: 0,
    expToLevel: 188,
    catchRate: 20,
    moves: ["Crash", "StringConcat", "Harden"]
  },
  {
    id: 83,
    name: "Cachoo",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 57,
    baseAtk: 60,
    baseDef: 50,
    baseSp: 55,
    baseSpd: 50,
    exp: 0,
    expToLevel: 188,
    catchRate: 20,
    moves: ["DataShift", "LeakDetect", "Scratch"]
  },
  {
    id: 84,
    name: "Invaria",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 62,
    baseAtk: 59,
    baseDef: 51,
    baseSp: 53,
    baseSpd: 40,
    exp: 0,
    expToLevel: 188,
    catchRate: 20,
    moves: ["IfStatement", "BooleanFlip", "Harden"]
  },
  {
    id: 85,
    name: "Torrenta",
    type: CODEMON_TYPES.FLOW,
    baseHp: 53,
    baseAtk: 60,
    baseDef: 48,
    baseSp: 55,
    baseSpd: 44,
    exp: 0,
    expToLevel: 188,
    catchRate: 20,
    moves: ["CallbackStrike", "AsyncWave", "Recover"]
  },
  {
    id: 86,
    name: "Molting",
    type: CODEMON_TYPES.BUG,
    baseHp: 54,
    baseAtk: 49,
    baseDef: 50,
    baseSp: 45,
    baseSpd: 48,
    exp: 0,
    expToLevel: 191,
    catchRate: 20,
    moves: ["Scratch", "Bite", "Scratch"]
  },
  {
    id: 87,
    name: "Patchwork",
    type: CODEMON_TYPES.CODE,
    baseHp: 62,
    baseAtk: 57,
    baseDef: 56,
    baseSp: 56,
    baseSpd: 43,
    exp: 0,
    expToLevel: 191,
    catchRate: 20,
    moves: ["DebugAttack", "StringConcat", "Recover"]
  },
  {
    id: 88,
    name: "Dumpling",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 51,
    baseAtk: 54,
    baseDef: 55,
    baseSp: 54,
    baseSpd: 50,
    exp: 0,
    expToLevel: 191,
    catchRate: 20,
    moves: ["LeakDetect", "CacheStore", "Tackle"]
  },
  {
    id: 89,
    name: "Provable",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 54,
    baseAtk: 47,
    baseDef: 56,
    baseSp: 48,
    baseSpd: 50,
    exp: 0,
    expToLevel: 191,
    catchRate: 20,
    moves: ["BooleanFlip", "LogicalAnd", "Recover"]
  },
  {
    id: 90,
    name: "Confluen",
    type: CODEMON_TYPES.FLOW,
    baseHp: 56,
    baseAtk: 52,
    baseDef: 46,
    baseSp: 56,
    baseSpd: 46,
    exp: 0,
    expToLevel: 191,
    catchRate: 20,
    moves: ["PromiseChain", "AsyncWave", "Tackle"]
  },
  {
    id: 91,
    name: "Cocoona",
    type: CODEMON_TYPES.BUG,
    baseHp: 62,
    baseAtk: 48,
    baseDef: 55,
    baseSp: 46,
    baseSpd: 51,
    exp: 0,
    expToLevel: 194,
    catchRate: 20,
    moves: ["Bite", "Scratch", "Tackle"]
  },
  {
    id: 92,
    name: "Threadle",
    type: CODEMON_TYPES.CODE,
    baseHp: 60,
    baseAtk: 50,
    baseDef: 53,
    baseSp: 54,
    baseSpd: 43,
    exp: 0,
    expToLevel: 194,
    catchRate: 20,
    moves: ["StringConcat", "Crash", "Scratch"]
  },
  {
    id: 93,
    name: "Residue",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 54,
    baseAtk: 56,
    baseDef: 49,
    baseSp: 54,
    baseSpd: 44,
    exp: 0,
    expToLevel: 194,
    catchRate: 20,
    moves: ["CacheStore", "LeakDetect", "Scratch"]
  },
  {
    id: 94,
    name: "Quantifi",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 57,
    baseAtk: 52,
    baseDef: 44,
    baseSp: 51,
    baseSpd: 56,
    exp: 0,
    expToLevel: 194,
    catchRate: 20,
    moves: ["LogicalAnd", "StackOverflow", "Recover"]
  },
  {
    id: 95,
    name: "Deltoid",
    type: CODEMON_TYPES.FLOW,
    baseHp: 63,
    baseAtk: 51,
    baseDef: 51,
    baseSp: 51,
    baseSpd: 44,
    exp: 0,
    expToLevel: 194,
    catchRate: 20,
    moves: ["AsyncWave", "CallbackStrike", "Tackle"]
  },
  {
    id: 96,
    name: "Stingle",
    type: CODEMON_TYPES.BUG,
    baseHp: 61,
    baseAtk: 51,
    baseDef: 54,
    baseSp: 45,
    baseSpd: 51,
    exp: 0,
    expToLevel: 197,
    catchRate: 20,
    moves: ["Scratch", "Bite", "Scratch"]
  },
  {
    id: 97,
    name: "Binaro",
    type: CODEMON_TYPES.CODE,
    baseHp: 58,
    baseAtk: 47,
    baseDef: 54,
    baseSp: 46,
    baseSpd: 40,
    exp: 0,
    expToLevel: 197,
    catchRate: 20,
    moves: ["Crash", "StringConcat", "Recover"]
  },
  {
    id: 98,
    name: "Retaino",
    type: CODEMON_TYPES.MEMORY,
    baseHp: 53,
    baseAtk: 51,
    baseDef: 52,
    baseSp: 45,
    baseSpd: 49,
    exp: 0,
    expToLevel: 197,
    catchRate: 20,
    moves: ["DataShift", "CacheStore", "Harden"]
  },
  {
    id: 99,
    name: "Lambdra",
    type: CODEMON_TYPES.LOGIC,
    baseHp: 60,
    baseAtk: 58,
    baseDef: 52,
    baseSp: 46,
    baseSpd: 47,
    exp: 0,
    expToLevel: 197,
    catchRate: 20,
    moves: ["StackOverflow", "IfStatement", "Recover"]
  },
  {
    id: 100,
    name: "Estuary",
    type: CODEMON_TYPES.FLOW,
    baseHp: 51,
    baseAtk: 51,
    baseDef: 45,
    baseSp: 44,
    baseSpd: 56,
    exp: 0,
    expToLevel: 197,
    catchRate: 20,
    moves: ["CallbackStrike", "PromiseChain", "Recover"]
  },
];

const MOVE_POOL = {
  'Scratch': { power: 12, accuracy: 100, type: 'normal', category: 'physical' },
  'StringConcat': { power: 15, accuracy: 90, type: 'code', category: 'special' },
  'Bite': { power: 18, accuracy: 85, type: 'bug', category: 'physical' },
  'Crash': { power: 28, accuracy: 75, type: 'code', category: 'special' },
  'StackOverflow': { power: 32, accuracy: 70, type: 'logic', category: 'special' },
  'DebugAttack': { power: 24, accuracy: 95, type: 'code', category: 'physical' },
  'CacheStore': { power: 20, accuracy: 100, type: 'memory', category: 'special' },
  'DataShift': { power: 18, accuracy: 95, type: 'memory', category: 'physical' },
  'LeakDetect': { power: 25, accuracy: 80, type: 'memory', category: 'special' },
  'IfStatement': { power: 16, accuracy: 100, type: 'logic', category: 'special' },
  'BooleanFlip': { power: 14, accuracy: 100, type: 'logic', category: 'special' },
  'LogicalAnd': { power: 22, accuracy: 90, type: 'logic', category: 'physical' },
  'AsyncWave': { power: 20, accuracy: 100, type: 'flow', category: 'special' },
  'CallbackStrike': { power: 26, accuracy: 85, type: 'flow', category: 'physical' },
  'PromiseChain': { power: 30, accuracy: 75, type: 'flow', category: 'special' },
  'Tackle': { power: 10, accuracy: 100, type: 'normal', category: 'physical' },
  'Recover': { power: 0, accuracy: 100, type: 'normal', category: 'status', isHealing: true },
  'Harden': { power: 0, accuracy: 100, type: 'normal', category: 'status', isDefensive: true }
};

class Codemon {
  constructor(species, level = 1) {
    this.species = species;
    this.level = level;
    this.exp = 0;
    this.expToLevel = species.expToLevel;
    this.hp = this.getMaxHp();
    this.currentHp = this.hp;
    this.moves = [...species.moves];
    this.stats = {
      atk: this.getAtk(),
      def: this.getDef(),
      sp: this.getSp(),
      spd: this.getSpd()
    };
    this.id = Math.random().toString(36).substr(2, 9);
  }

  getMaxHp() {
    return Math.floor((2 * this.species.baseHp * this.level) / 100 + this.level + 5);
  }

  getAtk() {
    return Math.floor((2 * this.species.baseAtk * this.level) / 100 + 5);
  }

  getDef() {
    return Math.floor((2 * this.species.baseDef * this.level) / 100 + 5);
  }

  getSp() {
    return Math.floor((2 * this.species.baseSp * this.level) / 100 + 5);
  }

  getSpd() {
    return Math.floor((2 * this.species.baseSpd * this.level) / 100 + 5);
  }

  learnMove(moveName) {
    if (this.moves.length < 4 && !this.moves.includes(moveName)) {
      this.moves.push(moveName);
    }
  }

  gainExp(amount) {
    this.exp += amount;
    while (this.exp >= this.expToLevel) {
      this.levelUp();
    }
  }

  levelUp() {
    this.exp -= this.expToLevel;
    this.level++;
    this.expToLevel = Math.floor(this.expToLevel * 1.1);
    this.hp = this.getMaxHp();
    this.currentHp = this.hp;
    this.stats.atk = this.getAtk();
    this.stats.def = this.getDef();
    this.stats.sp = this.getSp();
    this.stats.spd = this.getSpd();
  }

  takeDamage(damage) {
    this.currentHp = Math.max(0, this.currentHp - damage);
  }

  heal(amount) {
    this.currentHp = Math.min(this.hp, this.currentHp + amount);
  }

  getMove(moveName) {
    return MOVE_POOL[moveName];
  }
}

class Player {
  constructor() {
    this.level = 1;
    this.exp = 0;
    this.gold = 100;
    this.team = [];
    this.pokedex = new Set();
    this.items = {
      pokeball: 5,
      greatball: 2,
      potion: 3,
      antidote: 1
    };
  }

  addCodemon(codemon) {
    if (this.team.length < 6) {
      this.team.push(codemon);
      this.pokedex.add(codemon.species.id);
      return true;
    }
    return false;
  }

  getActiveCodemon() {
    return this.team.length > 0 ? this.team[0] : null;
  }

  switchCodemon(index) {
    if (index >= 0 && index < this.team.length && this.team[index].currentHp > 0) {
      [this.team[0], this.team[index]] = [this.team[index], this.team[0]];
      return true;
    }
    return false;
  }

  usePotion() {
    if (this.items.potion > 0) {
      const active = this.getActiveCodemon();
      if (active && active.currentHp < active.hp) {
        active.heal(20);
        this.items.potion--;
        return true;
      }
    }
    return false;
  }

  useItem(itemType) {
    if (this.items[itemType] > 0) {
      this.items[itemType]--;
      return true;
    }
    return false;
  }

  addGold(amount) {
    this.gold += amount;
  }

  addExp(amount) {
    this.exp += amount;
  }
}

window.Codemon = Codemon;
window.Player = Player;
window.CODEMON_SPECIES = CODEMON_SPECIES;
window.MOVE_POOL = MOVE_POOL;
